services:
  app:
    build:
      context: .
      dockerfile: docker/php-fpm.Dockerfile
    image: olx-watcher-app:latest
    container_name: olx-watcher-app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    environment:
      - APP_ENV=local
    depends_on:
      - mysql
      - redis
      - mailhog

  web:
    image: nginx:alpine
    container_name: olx-watcher-web
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - app

  queue:
    image: olx-watcher-app:latest
    container_name: olx-watcher-queue
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
      - redis

  scheduler:
    image: olx-watcher-app:latest
    container_name: olx-watcher-scheduler
    command: sh -lc "cp -r /overlay/* /var/www/html && php artisan schedule:work"
    volumes:
      - ./:/var/www/html
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: olx-watcher-mysql
    environment:
      MYSQL_DATABASE: olx
      MYSQL_USER: olx
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: olx-watcher-redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  app-data:
  db-data:
